# Generated by Django 3.0.8 on 2020-07-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.CharField(max_length=10)),
                ('c_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('goods', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=20, null=True)),
                ('c_type', models.CharField(choices=[('', 'Select an option'), ('L', 'Land'), ('A', 'Air'), ('O', 'Ocean')], max_length=10)),
                ('destination', models.CharField(max_length=50)),
                ('destination_address', models.TextField(max_length=150, null=True)),
                ('destination_pincode', models.IntegerField(null=True)),
                ('origin', models.CharField(max_length=50)),
                ('origin_address', models.TextField(max_length=150, null=True)),
                ('origin_pincode', models.IntegerField(null=True)),
                ('ctr_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('q_message', models.TextField(max_length=400)),
            ],
        ),
    ]
