# Generated by Django 3.0.8 on 2020-08-02 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotes',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='quotes',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
